version: 2
jobs:
  build:
    docker:
     
      - image: circleci/python:3.6.1
      

    working_directory: ~/hello

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv hello
            . hello/bin/activate
            make install
      - save_cache:
          paths:
            - ./hello
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      #- run:
       #   name: run tests
      #    command: |
        #    . venv/bin/activate
        #    make test
      # run lints!
      - run:
          name: run lint
          command: |
            . hello/bin/activate
            make lint
